import React, { useEffect, useState } from 'react';
import api from '../api';
import ContextGuide from '../components/ContextGuide';

function Maintenance() {
	const [equipment, setEquipment] = useState([]);
	const [maintenance, setMaintenance] = useState([]);
	const [error, setError] = useState('');
	const [form, setForm] = useState({ equipmentId: '', maintenanceDate: '', nextDueDate: '', cost: '', description: '', status: 'SCHEDULED' });
	useEffect(() => { Promise.all([api.get('/equipment'), api.get('/maintenance')]).then(([equipmentResponse, maintenanceResponse]) => { setEquipment(equipmentResponse.data); setMaintenance(maintenanceResponse.data); setForm(current => ({ ...current, equipmentId: equipmentResponse.data[0] ? String(equipmentResponse.data[0].id) : '' })); }).catch(() => setError('Unable to load maintenance data.')); }, []);
	const handleSubmit = async event => { event.preventDefault(); try { await api.post(`/maintenance?equipmentId=${form.equipmentId}`, { maintenanceDate: form.maintenanceDate, nextDueDate: form.nextDueDate, cost: form.cost ? Number(form.cost) : null, description: form.description, status: form.status }); const response = await api.get('/maintenance'); setMaintenance(response.data); setForm(current => ({ ...current, maintenanceDate: '', nextDueDate: '', cost: '', description: '' })); } catch (err) { setError(err.response?.data?.message || 'Unable to save maintenance.'); } };
	const deleteMaintenance = async id => { try { await api.delete(`/maintenance/${id}`); setMaintenance(maintenance.filter(item => item.id !== id)); } catch (err) { setError('Unable to delete maintenance record.'); } };
	return (
		<div className="workspace-page">
			<p className="eyebrow">Stay ahead</p>
			<h2>Maintenance</h2>
			<ContextGuide eyebrow="Protect your uptime" title="Schedule service before it becomes urgent." description="Use maintenance dates and service notes to keep your equipment dependable through the busiest weeks." actions={[{ label: 'View equipment', to: '/equipment' }, { label: 'Open dashboard', to: '/dashboard' }]} />
			{error && <div className="alert alert-danger">{error}</div>}
			{!equipment.length ? <div className="alert alert-info">Add equipment first, then schedule maintenance.</div> : <><div className="card shadow-sm border-0 mb-4"><div className="card-body"><form onSubmit={handleSubmit}><div className="row g-3"><div className="col-md-3"><label className="form-label">Equipment</label><select className="form-select" value={form.equipmentId} onChange={event => setForm({ ...form, equipmentId: event.target.value })}>{equipment.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="col-md-2"><label className="form-label">Service Date</label><input type="date" className="form-control" value={form.maintenanceDate} onChange={event => setForm({ ...form, maintenanceDate: event.target.value })} required /></div><div className="col-md-2"><label className="form-label">Next Due</label><input type="date" className="form-control" value={form.nextDueDate} onChange={event => setForm({ ...form, nextDueDate: event.target.value })} required /></div><div className="col-md-2"><label className="form-label">Cost</label><input type="number" min="0" step="0.01" className="form-control" value={form.cost} onChange={event => setForm({ ...form, cost: event.target.value })} /></div><div className="col-md-2"><label className="form-label">Status</label><select className="form-select" value={form.status} onChange={event => setForm({ ...form, status: event.target.value })}><option>SCHEDULED</option><option>COMPLETED</option><option>CANCELLED</option></select></div><div className="col-md-1 d-flex align-items-end"><button className="btn btn-success">Add</button></div><div className="col-12"><label className="form-label">Description</label><input className="form-control" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></div></div></form></div></div><div className="card shadow-sm border-0"><div className="table-responsive"><table className="table table-hover mb-0"><thead className="table-light"><tr><th>Equipment</th><th>Service Date</th><th>Next Due</th><th>Cost</th><th>Status</th><th>Description</th><th /></tr></thead><tbody>{maintenance.map(item => <tr key={item.id}><td>{item.equipment?.name || 'Equipment'}</td><td>{item.maintenanceDate}</td><td>{item.nextDueDate}</td><td>{item.cost ?? '-'}</td><td>{item.status}</td><td>{item.description || '-'}</td><td><button className="btn btn-sm btn-outline-danger" onClick={() => deleteMaintenance(item.id)}>Delete</button></td></tr>)}{!maintenance.length && <tr><td colSpan="7" className="text-center py-3">No maintenance records yet.</td></tr>}</tbody></table></div></div></>}
		</div>
	);
}
export default Maintenance;
